name: Check angular app
description: "Composite action - check angular app"

runs:
  using: "composite"
  steps:
    - name: Build lib
      run: npm run build:lib:prod
      shell: bash

    - name: Tests
      run: npm run test:prod
      shell: bash

    - name: Lint
      run: npm run lint:prod
      shell: bash
