name: Publish pages

on:
    workflow_call:
        inputs:
            branch:
                required: true
                type: string
            source: 
                required: true
                type: string

jobs:

    buildJekyll:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: '${{inputs.branch}}'

          - name: Setup Pages
            uses: actions/configure-pages@v3

          - name: Build with Jekyll
            uses: actions/jekyll-build-pages@v1
            with:
              source: ${{inputs.source}}
              destination: ./_site

          - name: Upload artifact
            uses: actions/upload-pages-artifact@v2
          
    deployJekyll:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: [buildJekyll]
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v2