name: UI Build + Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Run ci
        run: npm ci

      - name: ttas
        run: if [[ git status --porcelain ]]; then echo "changes" else echo "No changes!" fi

      - name: Run tests
        run: npm run test:prod

      - name: Run lint
        run: npm run lint:prod

      - name: Run build lib
        run: npm run build:lib:prod

      - name: Run build pages
        run: npm run build:test-view-app:ghpages

      # - name: Push and send notification
      #   run: |
      #       COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
      #       git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
      #       # Only if repo have changes
      #       git commit -m "${COMMIT_MESSAGE}"
      #       git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git master

      - name: Run publish pages
        run: |
            if [[ `git status --porcelain` ]]; then
              COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
              echo $COMMIT_MESSAGE
              git commit -m "${COMMIT_MESSAGE}"
              git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git master
            else
              echo "No changes!"