name: UI Build + Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Run ci
        run: npm ci

      - name: Tests
        run: npm run test:prod

      - name: Lint
        run: npm run lint:prod

      - name: Build lib
        run: npm run build:lib:prod

      - name: Build pages app
        run: npm run build:test-view-app:ghpages

      # - name: Push and send notification
      #   run: |
      #       COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
      #       git diff-index --quiet --cached HEAD -- && echo "No changes!" && exit 0 || echo $COMMIT_MESSAGE
      #       # Only if repo have changes
      #       git commit -m "${COMMIT_MESSAGE}"
      #       git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git master

      - name: Set git config and add changes
        run: |
            git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
            git config --global user.name "${GITHUB_ACTOR}"
            git add --all

      - name: Publish pages app
        run: |
            COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
            echo $COMMIT_MESSAGE
            git commit -m "${COMMIT_MESSAGE}"
            git push origin HEAD:pages --force
#            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_ACTOR}/ngx-compack.git pages
#            git push https://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@github.com/PkkDev/PkkDev.ngx-compack.git pages --force
           