name: Init angular project

on:
    workflow_call:
      inputs:
        node_version:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Run ci
        run: npm ci

      - name: Tests
        run: npm run test:prod

      - name: Lint
        run: npm run lint:prod