name: Test + Lint + Build + Pages

on:
  pull_request_target:
    types: ["closed"]
    branches: ["pages"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Run ci
        run: npm ci

      - name: Tests
        run: npm run test:prod

      - name: Lint
        run: npm run lint:prod

      - name: Build lib
        run: npm run build:lib:prod

      - name: Build pages app
        run: npm run build:test-view-app:ghpages

      - name: Set git config and add changes
        run: |
            git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
            git config --global user.name "${GITHUB_ACTOR}"
            git add --all

      - name: Publish pages app
        run: |
            COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
            echo $COMMIT_MESSAGE
            git commit -m "${COMMIT_MESSAGE}"
            git push

  buildJekyll:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
      
        
  deployJekyll:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build, buildJekyll]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

#git push origin HEAD:pages --force
